language: node_js
sudo: false

node_js:
  - "10"
  - "12"
  - "13"

cache: npm

git:
  depth: false

env:
  - NATS_VERSION=v2.0.0

before_script:
  - wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
  - unzip tmp.zip
  - mv nats-server-$NATS_VERSION-linux-amd64 nats-server

script:
  - if [[ "$TRAVIS_NODE_VERSION" == 10 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 12 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 13 ]]; then npm run coveralls; fi
